---
# Install and Configure Node Exporter
# Author: Adrian Johnson <adrian207@gmail.com>

- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    shell: /bin/false
    system: true
    create_home: false

- name: Download Node Exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version | default('1.7.0') }}/node_exporter-{{ node_exporter_version | default('1.7.0') }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'

- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp/
    remote_src: true

- name: Copy Node Exporter binary
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version | default('1.7.0') }}.linux-amd64/node_exporter"
    dest: /usr/local/bin/node_exporter
    mode: '0755'
    owner: node_exporter
    group: node_exporter
    remote_src: true

- name: Create Node Exporter systemd service
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Node Exporter
      Documentation=https://prometheus.io/docs/guides/node-exporter/
      After=network-online.target

      [Service]
      Type=simple
      User=node_exporter
      Group=node_exporter
      ExecStart=/usr/local/bin/node_exporter \
        --collector.systemd \
        --collector.processes
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'

- name: Enable and start Node Exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
    daemon_reload: true

- name: Clean up temporary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/node_exporter.tar.gz
    - "/tmp/node_exporter-{{ node_exporter_version | default('1.7.0') }}.linux-amd64"


