---
# Common Role - Base Configuration for All Servers
# Author: Adrian Johnson <adrian207@gmail.com>

- name: Set timezone
  community.general.timezone:
    name: America/New_York
  tags:
    - common
    - timezone

- name: Update system packages
  ansible.builtin.package:
    name: "*"
    state: latest
  when: ansible_os_family in ['Debian', 'RedHat']
  tags:
    - common
    - updates

- name: Install common packages
  ansible.builtin.package:
    name:
      - vim
      - curl
      - wget
      - git
      - htop
      - net-tools
      - tmux
      - rsync
      - unzip
      - jq
      - python3
      - python3-pip
    state: present
  tags:
    - common
    - packages

- name: Configure NTP
  ansible.builtin.package:
    name: chrony
    state: present
  tags:
    - common
    - ntp

- name: Start and enable chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: true
  tags:
    - common
    - ntp

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - common
    - hostname

- name: Configure /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    state: present
  loop: "{{ groups['all'] }}"
  tags:
    - common
    - hosts

- name: Disable SELinux (for lab environments)
  ansible.posix.selinux:
    state: disabled
  when: ansible_os_family == 'RedHat' and environment != 'prod'
  tags:
    - common
    - selinux

- name: Configure firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
  when: ansible_os_family == 'RedHat'
  tags:
    - common
    - firewall

- name: Create common directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/scripts
    - /opt/backups
    - /var/log/custom
  tags:
    - common
    - directories

- name: Install Node Exporter for monitoring
  ansible.builtin.include_tasks: install-node-exporter.yml
  tags:
    - common
    - monitoring


