# Ansible Inventory - Development Environment
# Author: Adrian Johnson <adrian207@gmail.com>

all:
  vars:
    ansible_user: azureuser
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    environment: dev
    domain: dev.contoso.com
    
management_tier:
  hosts:
    vault-01.dev.contoso.com:
      ansible_host: 10.10.10.20
      vault_node_id: 1
    vault-02.dev.contoso.com:
      ansible_host: 10.10.10.21
      vault_node_id: 2
    vault-03.dev.contoso.com:
      ansible_host: 10.10.10.22
      vault_node_id: 3
    dsc-pull-01.dev.contoso.com:
      ansible_host: 10.10.10.30
      dsc_node_type: primary
    dsc-pull-02.dev.contoso.com:
      ansible_host: 10.10.10.31
      dsc_node_type: secondary
    awx-01.dev.contoso.com:
      ansible_host: 10.10.10.40
  vars:
    tier: management
    subnet: 10.10.10.0/24

monitoring_tier:
  hosts:
    prometheus-01.dev.contoso.com:
      ansible_host: 10.10.20.10
    grafana-01.dev.contoso.com:
      ansible_host: 10.10.20.20
    alertmanager-01.dev.contoso.com:
      ansible_host: 10.10.20.30
  vars:
    tier: monitoring
    subnet: 10.10.20.0/24

data_tier:
  hosts:
    postgres-01.dev.contoso.com:
      ansible_host: 10.10.30.10
      postgresql_role: primary
      postgresql_replication_slot: postgres_01
    postgres-02.dev.contoso.com:
      ansible_host: 10.10.30.11
      postgresql_role: replica
      postgresql_replication_slot: postgres_02
  vars:
    tier: data
    subnet: 10.10.30.0/24

# Grouped by service
vault_cluster:
  hosts:
    vault-01.dev.contoso.com:
    vault-02.dev.contoso.com:
    vault-03.dev.contoso.com:
  vars:
    vault_version: "1.15.4"
    vault_cluster_name: "dev-vault-cluster"

dsc_pull_servers:
  hosts:
    dsc-pull-01.dev.contoso.com:
    dsc-pull-02.dev.contoso.com:
  vars:
    dsc_pull_server_url: "https://dsc.dev.contoso.com:8080/PSDSCPullServer.svc"

prometheus_servers:
  hosts:
    prometheus-01.dev.contoso.com:
  vars:
    prometheus_version: "2.48.0"
    prometheus_storage_retention: "30d"
    prometheus_storage_retention_size: "50GB"

grafana_servers:
  hosts:
    grafana-01.dev.contoso.com:
  vars:
    grafana_version: "10.2.2"
    grafana_admin_user: admin
    grafana_domain: grafana.dev.contoso.com

postgresql_cluster:
  hosts:
    postgres-01.dev.contoso.com:
    postgres-02.dev.contoso.com:
  vars:
    postgresql_version: "15"
    postgresql_max_connections: 200

# Linux nodes
linux_nodes:
  hosts:
    linux-node-[01:10].dev.contoso.com:
  vars:
    node_os_family: RedHat

# Windows nodes
windows_nodes:
  hosts:
    win-node-[01:10].dev.contoso.com:
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5986


