# Ansible Linting and Testing Pipeline
# Author: Adrian Johnson <adrian207@gmail.com>

name: Ansible Lint

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'ansible/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'ansible/**'

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      - name: Run yamllint
        run: yamllint ansible/
        continue-on-error: true

      - name: Run ansible-lint
        run: ansible-lint ansible/
        continue-on-error: true

  ansible-syntax-check:
    name: Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Ansible Syntax Check
        run: |
          cd ansible
          ansible-playbook playbooks/site.yml --syntax-check

  ansible-dry-run:
    name: Dry Run
    runs-on: ubuntu-latest
    needs: ansible-syntax-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Dry Run Playbooks
        run: |
          cd ansible
          ansible-playbook playbooks/site.yml --check --diff
        continue-on-error: true


